### ISSUE TITLE
Do I need merchant account to use the API ?

### ISSUE THREAD

**Issue by belgotux** [robvankeilegom/firefly-III-paypal-importer#10]
Hello,

I've got a problem to have the live transaction on paypal. I can only get sandbox API keys when going to https://developer.paypal.com/developer/applications.
Here the error and after a 404 on the [next page](https://www.paypal.com/merchantsignup/router/be/wps)

![image](https://user-images.githubusercontent.com/11537542/185722783-dfaee759-fc7e-4a06-8d74-51de85ce06f2.png)

It doesn't work with personnal paypal account ? Or my paypal account is weird ?

Sorry it's not very issue with your script but related, and I don't see the scope in the readme.

Regards,
Belgotux

**Comment by robvankeilegom** [comment]
@belgotux I looked into this and apparently you do. It looks like i have a business account, I'm not sure how i changed this, i definitely didn't request it myself via the developer portal. It must've done this automatically. 
Also in the developer portal it says `Current account type: Business`
![image](https://user-images.githubusercontent.com/13810300/187022454-587083fb-75b7-4648-96d9-c9807dfb7d64.png)
But via https://www.paypal.com/myaccount/settings/  it says `Upgrade to a Business account`
![image](https://user-images.githubusercontent.com/13810300/187022499-a3e8cd42-1902-4e78-9463-c11a84270570.png)

So i have no idea :smile:

**Comment by mgundelfinger** [comment]
I would like to add that it does work for me without a business account! \
In my developer portal it says `Current account type: Premier`, I am not sure how I got there or what that means, but I believe it might even be possible with a personal account.

![image](https://github.com/robvankeilegom/firefly-III-paypal-importer/assets/56203956/10766f07-940d-40aa-bfaa-aa650caa8408)

On the [Apps & Credentials](https://developer.paypal.com/dashboard/applications/sandbox) page, the Sandbox / Live slider is disabled, when I click it, it lets me know I have to upgrade to a business account in order to use it.

![image](https://github.com/robvankeilegom/firefly-III-paypal-importer/assets/56203956/d2fb306d-2bb2-4cf9-9049-3f431ca4957f)

However, on the same page, directly under the headling "API Credentials" is a large yellow banner that reads:

![image](https://github.com/robvankeilegom/firefly-III-paypal-importer/assets/56203956/7407a13a-3f37-428f-bc9b-6c4f40512e68)
Clicking on [View live credentials](https://developer.paypal.com/dashboard/applications/live) directly brings me to the "Live" page (it even moves the slider)
![image](https://github.com/robvankeilegom/firefly-III-paypal-importer/assets/56203956/5b86b8a1-2cc7-4b88-beb9-54b7920d2c88)

And here I can create and manage my apps. At first I (as many others) was not able to access the API but after a few hours i tried again and it all worked out!

**Comment by maxxer** [comment]
I'm wondering what will change when switching a _personal_ account to a _business_ one...

**Comment by fear025** [comment]
> I'm wondering what will change when switching a _personal_ account to a _business_ one...

Among other things, Personal Paypal Accounts are able to send money to friends and family without paying a fee. Business accounts are not able to do this.
